### PR TITLE
Read input registers and basic support of little Indian values

### PR DESCRIPTION
**Pull request by PhilippeRigaux**
To support Solax X1 G4 inverters, one need to decode little Indian numbers and read Input registers. Sample config file included..

### CODE REVIEW

**Comment by PhilippeRigaux** [comment]
Last minute bug fix on some little Indian values..

**Comment by mazocode** [comment]
Many thanks for contributing @PhilippeRigaux! Can you please check the output from the linter workflow and rename indianess/indian to endianness/endian?

**Comment by PhilippeRigaux** [comment]
I saw that you didn't managed the multi-bytes value in your initial code so I added it to big endian too.

**Comment by PhilippeRigaux** [comment]
What is the "linter workflow"?

**Comment by mazocode** [comment]
> What is the "linter workflow"?

You can run  `make check-code`  to run the linter. The linter is blocking a merge if there are code formatting issues. It's a bit picky but helps to ensure readability...

**Comment by PhilippeRigaux** [comment]
OK, saw the emails, currently fixing them..

**Comment by mazocode** [comment]
Looks good, thanks!

**Pull request merged**
